### ISSUE TITLE
Prophet AutoML never creates model with best parameters from Hyperopt

### ISSUE THREAD

**Issue by rbloehm** [databricks/automl#19]
There is a bug using the ProphetHyperParams enum in the AutoML implementation for forecasting with prophet.
**The metrics report the potentially very good best result from Hyperopt, but the stored model itself, the evaluation plots and the forecast results are completely unrelated and probably much worse.**

This leads to the following situation which happens every time someone uses Databricks AutoML for forecasting:
* Run Hyperopt, find a best set of parameters (best_result), for example: 
![image](https://user-images.githubusercontent.com/10888961/148073451-a6da3fd4-c83f-47ff-a001-c21db4387fd9.png)
note: seasonality_mode=1 is multiplicative.
* The metrics reported in Databricks AutoML & mlflow are the ones from this best_result. So far so good.
* The model that is then trained on the full dataset, evaluated in the Training notebook (plots etc.) and stored as artifact **has nothing to do with those selected hyperparameters**: 
![image](https://user-images.githubusercontent.com/10888961/148074030-0a98e8f6-2c03-49b6-9cf6-c2959a5b54ec.png)

**Potential reason / bug:**
https://github.com/databricks/automl/blob/242bf1afbff43a0f6e94e29bee7f01552489a004/runtime/databricks/automl_runtime/forecast/prophet/forecast.py#L150-L153
![image](https://user-images.githubusercontent.com/10888961/148074387-1be3ae12-f4b3-48cb-a046-278846c0ecfe.png)

Databricks Runtime 10.2 ML
databricks-automl-runtime==0.2.4

**Comment by wenfeiy-db** [comment]
@rbloehm Thanks for reporting this! It will be fixed in new release. We will also patch previous releases which were affected.

**Comment by rbloehm** [comment]
@wenfeiy-db I installed the new version 0.2.4.1 in one of our clusters and can confirm that the bug has been fixed. Thanks!
