### ISSUE TITLE
Model Addition Request [Feature]

### ISSUE THREAD

**Issue by bstuddard** [databricks/automl#75]
Two model additions that would be great to have in automl:

1) catboost - in addition to existing lightgbm and xgboost, could provide some benefits in handling categorical features directly.

2) Keras - even a constrained handful of architectures, adding deep learning to automl to at least identify when it performs well.

**Comment by Loquats** [comment]
Thanks for the suggestions! These are good features to add to automl, and we'll think about when to prioritize them. Could you also provide that feedback through [this form](https://databricks.sjc1.qualtrics.com/jfe/form/SV_cvX0PGMndISOnzM)?
