### ISSUE TITLE
Package compatibility: Numba needs NumPy 1.20 or less

### ISSUE THREAD

**Issue by ania-gousto** [databricks/automl#77]
Hello,
When running an AutoML experiment on a cluster with DataBricks runtime 9.1 LTS ML, I get the following error during the setup stage:
`Numba needs NumPy 1.20 or less`
These are the other libraries installed on the cluster: sqlalchemy, gensim, nltk, xgboost, awswrangler.

**Comment by Loquats** [comment]
AutoML requires specific library versions as dependencies. The other libraries installed on the cluster may conflict with automl's requirements, and cause it to fail. Could you try running automl on a clean 9.1 LTS ML cluster, and see if that fixes the issue?
